language: cpp

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - lcov
      - gfortran
      
script:
# tests
- cmake -H. -B_build -DBUILD_TESTS=ON
- cmake --build _build
- cmake --build _build --target test
- cmake --build _build --target test -- ARGS=--verbose

# examples
- cmake -H. -B_build -DBUILD_EXAMPLES=ON -DENABLE_COVERAGE=ON
- cmake --build _build
- cd _build
- make gcov
- make lcov
